# Generated by Django 4.0.4 on 2022-06-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_message_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.IntegerField(),
        ),
    ]
